# Generated by Django 2.0.5 on 2020-01-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='purchased_date',
        ),
    ]
